### ISSUE TITLE
App Transport Security

### ISSUE THREAD

**Issue by DarkAgeOutlaw** [Daltron/BigBoard#5]
I was wondering if there was a reason the query call to the Yahoo API is 'http' instead of 'https'. With Apple getting close in the future to requiring apps to use https is that possible to change. I know of the setting to turn this requirement off but it'd be nice not to have to ask Apple for special permission if it's not needed.

**Comment by Daltron** [comment]
Hi @DarkAgeOutlaw! 😄 Thanks for bringing this to my attention. I have updated the urls to use https instead of http. Running `pod update BigBoard` should pull down the latest changes and grab the latest version. Thanks!
