### ISSUE TITLE
504 timeout when retrieving chart data for a stock

### ISSUE THREAD

**Issue by dexterslabor** [Daltron/BigBoard#7]
I just discovered BigBoard and tried the example code.
Unfortunately the graphs are not working in the app as well as on github in the readme (error fetching resource). 
It appears to me that the Yahoo API might have changed?!

**Comment by Daltron** [comment]
Hey @dexterslabor! There have been multiple people report to me in the last couple days that something seems off. If I had to guess, either they are doing some major changes or they are officially going to be dropping support for this API. If I had to guess, the second one is probably more likely. If that is the case, then that is very unfortunate. I will search to see if I can find anything. 

Thanks!

**Comment by dexterslabor** [comment]
@Daltron thank you for your quick response. Would greatly appreciate any help in this regards

**Comment by Daltron** [comment]
The README has been updated to reflect issues within the Yahoo Finance API 👍
